### PR TITLE
Add 5.11

### PR DESCRIPTION
**Pull request by d-m-u**
... because this is one of the more useful documents, still, evaaaaaah :)

### CODE REVIEW

**Comment by d-m-u** [comment]
Hi @chrisarcand! Thanks! I think ... I _think_ these numbers should be right, but I spose you'll find out eventually if they're not :)

**Comment by chrisarcand** [comment]
@d-m-u  👋 You gotta change the application code along with the README change you've already committed.

**Comment by Fryguy** [comment]
And you have to unWIP it :)

**Comment by d-m-u** [comment]
Whoa, a stray Jason was watching this.

**Comment by chrisarcand** [comment]
🙇

**Pull request merged**
